name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install poetry
        run: pip install poetry==1.1.7
      - name: Install and run linters
        run: |
          poetry install
          poetry run pylint -E axiom tests
          poetry run black --check axiom tests
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup axiom
        uses: axiomhq/setup-axiom@v1
        id: axiom
      - name: Setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install poetry
        run: pip install poetry==1.1.7
      - name: Run tests
        env:
          AXIOM_URL: ${{ steps.axiom.outputs.url }}
          AXIOM_TOKEN: ${{ steps.axiom.outputs.token }}
        run: |
          poetry install
          poetry run python -m pytest